version: '3'

services:
  app:
    container_name: codingleo-production
    restart: always
    env_file: .env
    environment: 
      - NODE_ENV=production
      - BEHANCE_API_KEY=${BEHANCE_API_KEY}
      - FACEBOOK_APP_ID=${FACEBOOK_APP_ID}
      - SG_API_KEY=${SG_API_KEY}
      - SG_SECRET_KEY=${SG_SECRET_KEY}
      - SEND_EMAIL_TO=${SEND_EMAIL_TO}
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    links: 
      - mongo
      - redis
